### ISSUE TITLE
Images not been shown

### ISSUE THREAD

**Issue by a-ballesteros** [tstaerk/mediasyntax#12]
When trying [[Image:image_name]] the image, as well as the link, are broken.

For instance:
[[Image:motherboard.png]]

generates
< a href="/dokuwiki/lib/exe/detail.php?...&media=image:motherboard.png" ... >
< img src="/dokuwiki/lib/exe/fetch.php?media=image:motherboard.png" ... >< /a >

However, by removing "image:" manually, it works.

It it the same problem described in "https://github.com/tstaerk/mediasyntax/issues/3#issuecomment-951375"? Should I use the RewriteRules directive to fix this?

Thanks in advance!

**Comment by tstaerk** [comment]
How could this image showing thing ever work? Anyone knows?

**Comment by tstaerk** [comment]
fixed: https://github.com/tstaerk/mediasyntax/commit/d801a4eb5a10be6ab4a8d26e523b171dba3d4d20
