### ISSUE TITLE
Does not support html color

### ISSUE THREAD

**Issue by NeuralLink** [tstaerk/mediasyntax#15]
Syntax such as 
``` html
   <span style="color:#C90D00">'''''Needs clarification'''''</span>
```
does not convert.

Probably more of a feature request than a bug.

**Comment by tstaerk** [comment]
Good request, thanks.

I think span must be added to the "allowhtml" tags in dokuwiki then it may work, can you check?

**Comment by tstaerk** [comment]
I got the wished output by setting htmlok to '1' in local.conf, then using the syntax

<html><span style="color:#C90D00"></html>'''''Needs clarification'''''<html></span></html>

but this was not what you were asking for. Let this work in the back of my mind for today.

**Comment by tstaerk** [comment]
sorry the last comment is not displayed as I intended it to

**Comment by NeuralLink** [comment]
It didn't work for me.  

This is from my local.php
``` php
$conf['htmlok'] = 1;
```

I 'solved' the problem with a workaround.  I installed the "color syntax plugin" and just altered my code from: 
``` html
<span style="color:#C90D00">'''''Needs clarification'''''</span>
```
to
``` html
<color #C90D00>'''''Needs clarification'''''</color>
```
This produces the desired result.  It's suboptimal, but it works just fine.

**Comment by tstaerk** [comment]
Good that you found a work-around, however I want you to know I am working on a solution. Today was not possible, but next weekend hopefully.

**Comment by tstaerk** [comment]
I am not quite done but this should give you/me an idea how to proceed:
<?php
/**
 * Mediasyntax Plugin, span component
 * 
 * @license    GPL 2 (http://www.gnu.org/licenses/gpl.html)
 * @author     Esther Brunner <wikidesign@gmail.com>
 */
 
// must be run within Dokuwiki
if(!defined('DOKU_INC')) die();

if(!defined('DOKU_PLUGIN')) define('DOKU_PLUGIN',DOKU_INC.'lib/plugins/');
require_once(DOKU_PLUGIN.'syntax.php');
 
/**
 * All DokuWiki plugins to extend the parser/rendering mechanism
 * need to inherit from this class
 */
class syntax_plugin_mediasyntax_span extends DokuWiki_Syntax_Plugin 
{

  function getType(){ return 'protected'; }
  function getSort(){ return 32; }
  
  function connectTo($mode)
  {
    $this->Lexer->addEntryPattern(
      //'<span\>*?',
      '<span.*?>',
      $mode,
      'plugin_mediasyntax_span'
    );
  }
  
  function postConnect()
  {
    $this->Lexer->addExitPattern(
      '</span>',
      'plugin_mediasyntax_span'
    );
  }
    
  function handle($match, $state, $pos, &$handler) 
  {
    echo ("state is $state");
    echo ("match is ".htmlentities($match));
    return array($match, $state, $pos);
  }
 
  function render($mode, &$renderer, $data) 
  {
    // $data is the return value of handle
    GLOBAL $span;
    if($mode == 'xhtml')
    {
      //print_r($data); // data[1] is always state
      echo $data[1].":".htmlentities($data[0]);
      if (!$span) $renderer->doc .= "<span>";
      else $renderer->doc .= "</span>";
      if ($span) $span=false;
      else $span=true;
    }
    return false;
  }
}
     
//Setup VIM: ex: et ts=4 enc=utf-8 :

**Comment by tstaerk** [comment]
just committed https://github.com/tstaerk/mediasyntax/blob/master/syntax/span.php

**Comment by tstaerk** [comment]
So this works, but mediawiki syntax inside the thing (i.e. between <span> and </span>) does not work. I guess I should use a specialPattern and based on it in the render function directly write the opening and closing tag.

**Comment by tstaerk** [comment]
Fixed: https://github.com/tstaerk/mediasyntax/blob/master/syntax/span.php. Took me about 5 hours.
