### ISSUE TITLE
Doesn't seem to be a way to link a pdf

### ISSUE THREAD

**Issue by kevinclevenger** [tstaerk/mediasyntax#17]
[[Image:kevin:image.png]] works correctly but I can't get a PDF upload link to work at all. If using [[Image:kevin:file.pdf]] I just get a generic image icon. Also tried File: and Media: without success. 

Using current git source

**Comment by tstaerk** [comment]
thanks for testing the current git source! Sounds plausible and fixable.

**Comment by tstaerk** [comment]
Just looked how mediawiki handles pdf files. [[Image:2014.pdf]] results in the html code <a href="/thorsten/File:2014.pdf" title="File:2014.pdf">File:2014.pdf</a>... of course the /thorsten/ depends on your environment ;)

**Comment by tstaerk** [comment]
Ok, markdown messed up what I wanted to write. [[Image:2014.pdf]] results in the html code 

    <a href="/thorsten/File:2014.pdf" title="File:2014.pdf">File:2014.pdf</a>

**Comment by tstaerk** [comment]
Fixed with https://github.com/tstaerk/mediasyntax/commit/922dd96a45cacb85a14a2692e21ac87b943948db
