### ISSUE TITLE
undefined constant then - problem and solution

### ISSUE THREAD

**Issue by thecreator1970** [tstaerk/mediasyntax#25]
Hi,

I am using the mediasyntax-plugin of dokuwiki.
It is a very usefull plugin for me.

There is an error in this mediasyntax-plugin.
This results in the fault (on some web pages):
Warning: Use of undefined constant then - assumed 'then' (this will throw an Error in a future version of PHP) in D:\xampp\htdocs\dokuwiki\lib\plugins\mediasyntax\syntax\codeblock.php on line 56

Solution is changing this file as follows:
```
56c56
<           if ($match[$i-1] == "\n" && $match[$i] == " ") then ;
---
>           if ($match[$i-1] == "\n" && $match[$i] == " ") {;}
```

Can this be changed in the new version please?
Now I have to change it with each update.

Thank you,
Bart

**Comment by tstaerk** [comment]
sounds good, but I am very busy. Do you want to become maintainer of mediasyntax?

**Comment by tstaerk** [comment]
fixed today

**Comment by thecreator1970** [comment]
Thank you for the solution.


Op zo 26 aug. 2018 om 19:51 schreef Thorsten Staerk <
notifications@github.com>

**Comment by tstaerk** [comment]
well it was your solution ;)

**Comment by thecreator1970** [comment]
:-)

Op ma 27 aug. 2018 om 11:28 schreef Thorsten Staerk <
notifications@github.com>:
