### ISSUE TITLE
“FatalException: Array and string offset access syntax with curly braces is no longer supported” on PHP 8.2 FastCGI

### ISSUE THREAD

**Issue by AzureCloudMonk** [tstaerk/mediasyntax#33]
Hi Andi,

I finally got a chance to install your fixes, and now get a new error:

“dokuwiki\Exception\FatalException: Array and string offset access syntax with curly braces is no longer supported

An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the mediasyntax plugin.

More info has been written to the DokuWiki error log.”

Here is my DokuWiki error log once I install the latest plugin:

2023-06-29 12:27:30
E_COMPILE_ERROR: Array and string offset access syntax with curly braces is no longer supported
/home/USERNAME/devopscloud.io/lib/plugins/mediasyntax/helper.php(376)
#0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()

https://www.devopscloud.io/doku.php?id=dokuwiki

Discussion originally referenced here: https://forum.dokuwiki.org/d/21100-mediasyntax-on-jackrum-php82-attempt-to-assign-property-toplevel-id-on-null

Thanks.

Again, thanks for your help on this.

**Comment by tstaerk** [comment]
Hi, your patch is developed. You mentioned you were ready to pay for it?

**Comment by AzureCloudMonk** [comment]
Thank you for your awesome plugin. How can I PayPal you some money? How long did it take to fix it to work with PHP 8.x?  Will you update the code on GitHub?Thanks again,Cloud Monk Losang Jinpa.On Jul 10, 2023, at 11:17 AM, Thorsten Staerk ***@***.***> wrote:﻿
Hi, your patch is developed. You mentioned you were ready to pay for it?

**Comment by AzureCloudMonk** [comment]
Thank you for your awesome plugin. I sent you a private email via your website Google form https://www.staerk.de/thorsten. Please reply to with your email to PayPal you or other method. Thanks again. 🙏

**Comment by tstaerk** [comment]
for me, the issue does not occur any longer.
