### ISSUE TITLE
MediaSyntax "update flag" never cleared after update in the Admin Extension Manager UI

### ISSUE THREAD

**Issue by AzureCloudMonk** [tstaerk/mediasyntax#36]
When I use the Admin Extension Manager  (e.g. https://www.devopscloud.io/doku.php?id=start&do=admin&page=extension&tab=plugins) the MediaSyntax plugin always shows: "Update: New version 2023-07-29 is available." Even after I do the update, it still continues to list an update as available. It did this back in 2015 as well.

All of the other plugins I use clear the "update flag" within the Extension Manager UI, so to speak, after doing an update. 

Obviously, this is a very low priority item.

Thanks again.

**Comment by tstaerk** [comment]
thanks for the feedback. Maybe a bug in dokuwiki, not in mediasyntax. Will have a look.

**Comment by tstaerk** [comment]
I can reproduce the bug.

**Comment by tstaerk** [comment]
fixed

**Comment by tstaerk** [comment]
please verify

**Comment by AzureCloudMonk** [comment]
Nice. Fixed. Thank you.
